-- Item-specific rules. Runtime also checks the quest log for required turn-in items.
-- never: always keep (class tools, mounts, etc.)
-- quests + safeWhenAllComplete: trash once every listed quest is flagged complete
-- optional: safe to delete if you are skipping that content

QuestJunkData = {
    never = {
        [6948] = "Hearthstone",
        [5175] = "Shaman class totem",
        [5176] = "Shaman class totem",
        [5177] = "Shaman class totem",
        [5178] = "Shaman class totem",
        [29744] = "Gray Elekk mount item",
        [28481] = "Brown Elekk mount item",
        [29220] = "Swift Green Hawkstrider mount item",
        [29221] = "Swift Purple Hawkstrider mount item",
        [29222] = "Swift Warstrider mount item",
        [29223] = "Swift Pink Hawkstrider mount item",
        [29224] = "Swift Olive Hawkstrider mount item",
    },

    optional = {
        [8623] = { note = "OOX-17/TN Distress Beacon — only needed for the chicken escort" },
        [8624] = { note = "OOX-09/HL Distress Beacon — only needed for the chicken escort" },
        [8625] = { note = "OOX-22/FE Distress Beacon — only needed for the chicken escort" },
    },

    -- Known leftover quest items once the chain is done.
    rules = {
        [4506] = { quests = { 682 }, note = "Stromgarde Badges turn-in leftover" },
        [24278] = { quests = { 9711 }, note = "Matis the Cruel flare gun" },
        [8593] = { quests = { 10 }, note = "Scrimshank surveying gear leftover" },
        [8594] = { quests = { 10 }, note = "Scrimshank surveying gear leftover" },
        [8595] = { quests = { 10 }, note = "Scrimshank surveying gear leftover" },
        [8596] = { quests = { 10 }, note = "Scrimshank surveying gear leftover" },
        [8597] = { quests = { 10 }, note = "Scrimshank surveying gear leftover" },
        [8598] = { quests = { 10 }, note = "Scrimshank surveying gear leftover" },
        [8599] = { quests = { 10 }, note = "Scrimshank surveying gear leftover" },
        [8600] = { quests = { 10 }, note = "Scrimshank surveying gear leftover" },
        [8601] = { quests = { 10 }, note = "Scrimshank surveying gear leftover" },
        [8602] = { quests = { 10 }, note = "Scrimshank surveying gear leftover" },
        [932] = { quests = { 179 }, note = "Fel Steed Saddlebags leftover" },
    },

    -- Harvested from ZygorGuidesViewerClassicTBCAnniv's own guide data: every
    -- item its `trash ItemName##ID` step goal calls out across the Leveling
    -- and Dungeon guides (Alliance + Horde). Zygor places these steps after
    -- the relevant quest chain, so no quest-gating check is needed here the
    -- way `rules` above requires it — unlike `rules`, always classifies as
    -- safe once found. `never` is still checked first, so anything in both
    -- lists (e.g. Hearthstone, which briefly showed up in Zygor's own data
    -- under a "future" flag) stays protected.
    zygorTrash = {
        [1468] = "Murloc Fin",
        [1532] = "Shrunken Head",
        [1962] = "Glowing Shadowhide Pendant",
        [2154] = "The Story of Morgan Ladimore",
        [2251] = "Gooey Spider Leg",
        [2633] = "Jungle Remedy",
        [3248] = "Translated Letter from The Embalmer",
        [3404] = "Buzzard Wing",
        [3898] = "Library Scrip",
        [4529] = "Enchanted Agate",
        [4589] = "Long Elegant Feather",
        [4702] = "Prospector's Pick",
        [4823] = "Water of the Seers",
        [5068] = "Dried Seeds",
        [5085] = "Bristleback Quilboar Tusk",
        [5088] = "Control Console Operating Manual",
        [5165] = "Sunscale Feather",
        [5251] = "Phial of Scrying",
        [5505] = "Teronis' Journal",
        [5570] = "Deepmoss Egg",
        [5838] = "Kodo Skin Scroll",
        [5866] = "Sample of Indurium Ore",
        [5877] = "Cracked Silithid Carapace",
        [5884] = "Unpopped Darkmist Eye",
        [6929] = "Bath'rah's Parchment",
        [7442] = "Gyromast's Key",
        [7846] = "Crag Coyote Fang",
        [8051] = "Flare Gun",
        [8066] = "Fizzule's Whistle",
        [8484] = "Gadgetzan Water Co. Care Package",
        [8523] = "Field Testing Kit",
        [8524] = "Model 4711-FTZ Power Source",
        [9369] = "Iridescent Sprite Darter Wing",
        [9460] = "Grimtotem Horn",
        [10444] = "Standard Issue Flare Gun",
        [10515] = "Torch of Retribution",
        [11018] = "Un'Goro Soil",
        [11108] = "Faded Photograph",
        [11184] = "Blue Power Crystal",
        [11185] = "Green Power Crystal",
        [11186] = "Red Power Crystal",
        [11188] = "Yellow Power Crystal",
        [11445] = "Flute of the Ancients",
        [11482] = "Crystal Pylon User's Manual",
        [11511] = "Cenarion Beacon",
        [11515] = "Corrupted Soul Shard",
        [11516] = "Cenarion Plant Salve",
        [11804] = "Spraggle's Canteen",
        [12341] = "Blackwood Fruit Sample",
        [12342] = "Blackwood Grain Sample",
        [12343] = "Blackwood Nut Sample",
        [12347] = "Filled Cleansing Bowl",
        [12814] = "Flame in a Bottle",
        [12815] = "Beacon Torch",
        [12891] = "Jaron's Pick",
        [15043] = "Plagueland Termites",
        [16784] = "Sapphire of Aku'Mai",
        [22644] = "Crunchy Spider Leg",
        [23695] = "Featherbeard's Map",
        [23984] = "Irradiated Crystal Shard",
        [24475] = "Gordawg's Imprint",
        [25719] = "Arakkoa Feather",
        [25745] = "Olemba Seed",
        [25766] = "\"Creatures That Owe Sal'salabim Golds\"",
        [28664] = "Nitrin's Instructions",
        [29443] = "Bloodmaul Brutebane Brew",
        [29590] = "Burning Legion Missive",
        [30425] = "Bleeding Hollow Blood",
        [30655] = "Infused Vekh'nir Crystal",
        [31121] = "Costume Scraps",
        [31347] = "Bleeding Hollow Torch",
        [31754] = "Grisly Totem",
        [31812] = "Doom Skull",
        [31828] = "Ritual Prayer Beads",
        [33040] = "Repaired Diving Gear",
    },
}